name: Build and publish ApiMock

on:
    repository_dispatch:
        types: [release-published]

env:
    DOCKER_HUB_DOMAIN: "openbankingbrasil"

    ADMIN_API_PORT: "7001"
    CHANNELS_API_PORT: "7002"
    COMMON_API_PORT: "7003"
    PRODUCTS_SERVICES_API_PORT: "7004"
jobs:

  build:

    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout openbanking repo
        uses: actions/checkout@v2
        with:
            repository: ${{ github.event.client_payload.repository }}
            ref:  ${{ github.event.client_payload.tagName }}
            path: openbanking        
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKER_HUB_USER_OPENBANKING }}
          password: ${{ secrets.DOCKER_HUB_TOKEN_OPENBANKING }}
                
      - uses: docker/setup-buildx-action@v1   
        with:
            buildkitd-flags: --debug      
        
      - name: Build and push docker image for Open Banking Admin Api
        id: docker_build_admin_api
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: ${{ env.DOCKER_HUB_DOMAIN }}/admin-api:${{ github.event.client_payload.tagName }}
          build-args: |
            api_swagger_path=openbanking/documentation/source/swagger/swagger_admin_apis.yaml
            api_port=${{ env.ADMIN_API_PORT }}
          push: true
        
      - name: Build and push docker image for Open Banking Channels Api
        id: docker_build_channels_api
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: ${{ env.DOCKER_HUB_DOMAIN }}/channels-api:${{ github.event.client_payload.tagName }}
          build-args: |
            api_swagger_path=openbanking/documentation/source/swagger/swagger_channels_apis.yaml
            api_port=${{ env.CHANNELS_API_PORT }}
          push: true
        
      - name: Build and push docker image for Open Banking Common Api
        id: docker_build_common_api
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: ${{ env.DOCKER_HUB_DOMAIN }}/common-api:${{ github.event.client_payload.tagName }}
          build-args: |
            api_swagger_path=openbanking/documentation/source/swagger/swagger_common_apis.yaml
            api_port=${{ env.COMMON_API_PORT }}
          push: true
        
      - name: Build and push docker image for Open Banking Products Services Api
        id: docker_build_products_services_api
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: ${{ env.DOCKER_HUB_DOMAIN }}/products-services-api:${{ github.event.client_payload.tagName }}
          build-args: |
            api_swagger_path=openbanking/documentation/source/swagger/swagger_products_services_apis.yaml
            api_port=${{ env.PRODUCTS_SERVICES_API_PORT }}
          push: true

      - name: Update version mock in file
        run: |
          echo API_VERSION=${{ github.event.client_payload.tagName }} > .env
          git config user.name build-and-publish-mock
          git config user.email build-and-publish-mockgithub.com
          git add .
          git commit -m "Update arquivo .env"
          git push
